name: Build Theme

on:
  push:
    branches:
      - main

jobs:
  build-theme:
    name: Build Theme
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Lint Code
        run: npm run lint
      - name: Build
        run: npm run build-theme
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(dist): new build"
