name: Distribute Theme

on:
  push:
    branches:
      - main

jobs:
  distribute-theme:
    name: Distribute Theme
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - name: Install Dependencies
        run: pnpm install
      - name: Build Theme
        run: |
          pnpm build
      - name: Copy Assets
        run: |
          cp -r src/assets dist
      - name: Deploy Changes
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: dist
          publish_dir: dist
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "chore: update"
