name: Distribute Theme

on:
  push:
    branches:
      - main

jobs:
  distribute-theme:
    name: Distribute Theme
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Build Theme
        run: |
          npm run build-theme
          mv dist/* .
      - name: Copy Assets
        run: |
          mkdir -p assets
          cp -r src/assets/* assets
      - name: Distribute files to dist branch
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: main
          branches: dist
          files: assets/* dist/*
